FROM node:16.15.0 AS builder

WORKDIR /sky-lark
RUN npm config set registry https://registry.npm.taobao.org
RUN npm install -g pnpm
COPY . ./
RUN pnpm i
RUN pnpm run build:pro

FROM nginx

COPY --from=builder /sky-lark/nginx.conf /etc/nginx/nginx.conf

EXPOSE 80

ENTRYPOINT [ "pnpm", "run", "start" ]
