FROM node:16.15.0 AS builder

WORKDIR /sky-lark
RUN npm config set registry https://registry.npm.taobao.org
RUN npm install -g pnpm
COPY . .
RUN pnpm i
RUN pnpm run build:dev

FROM builder AS runner

WORKDIR /sky-lark
COPY --from=builder /sky-lark/.output ./.output
EXPOSE 5314
