FROM node:16.15.0

WORKDIR /sky-lark-development

COPY package.json ./
COPY pnpm-lock.yaml ./

RUN npm config set registry https://registry.npm.taobao.org

RUN npm install -g pnpm

COPY . ./

RUN pnpm i

RUN pnpm run build:dev

EXPOSE 5314

ENTRYPOINT [ "pnpm", "run", "start" ]
